version: "3"
services:
        proxy:
                build: ./cors-proxy
                ports:
                        - '9898:9898'
        backend:
                build: './backend'
                ports:
                        - '3001:3001'

