export const INVALID_STATION = "INVALID_STATION"
export const STORAGE_FAIL = "STORAGE_FAIL"

export const ADD_DESTINATION = "ADD_DESTINATION"
export const ADD_DESTINATION_SUCCESS = "ADD_DESTINATION_SUCCESS"
export const ADD_DESTINATION_FAILED = "ADD_DESTINATION_FAILED"

export const GET_DESTINATION = "GET_DESTINATION"
export const GET_DESTINATION_SUCCESS = "GET_DESTINATION_SUCCESS"
export const GET_DESTINATION_FAILED = "GET_DESTINATION_FAILED"
