export const GET_STATIONS = 'GET_STATIONS'
export const GET_DEPARTURES = 'GET_DEPARTURES'
export const GET_CLOSEST_STATIONS = 'GET_CLOSEST_STATIONS'
export const FETCH_STATION_FAILED = "FETCH_STATION_FAILED"
export const FETCH_STATION_SUCCESS = "FETCH_STATION_SUCCESS"
export const SET_CLOSEST_STATION = "SET_CLOSEST_STATION"
