export const GET_STATIONS = 'GET_STATIONS'
export const GET_DEPARTURES = 'GET_DEPARTURES'
export const GET_DEPARTURES_FAILED = "GET_DEPARTURES_FAILED"
export const GET_DEPARTURES_SUCCESS = "GET_DEPARTURES_SUCCESS"

export const GET_CLOSEST_STATIONS = 'GET_CLOSEST_STATIONS'
export const FETCH_STATION_FAILED = "FETCH_STATION_FAILED"
export const FETCH_STATION_SUCCESS = "FETCH_STATION_SUCCESS"
export const SET_CLOSEST_STATION = "SET_CLOSEST_STATION"
export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION"

export const GET_CONNECTION = "GET_CONNECTION"
export const GET_CONNECTION_SUCCESS = "GET_CONNECTION_SUCCESS"
export const GET_CONNECTION_FAILED = "GET_CONNECTION_FAILED"

export const GET_LINE = "GET_LINE"
export const GET_LINE_SUCCESS = "GET_LINE_SUCCESS"
export const GET_LINE_FAILED = "GET_LINE_FAILED"
export const GET_LINE_ENCODING = "GET_LINE_ENCODING"
export const GET_LINE_ENCODING_SUCCESS = "GET_LINE_ENCODING_SUCCESS"
export const GET_LINE_ENCODING_FAILED = "GET_LINE_ENCODING_FAILED"

export const COMPUTE_LINE_SEGMENT = "COMPUTE_LINE_SEGMENT"
export const SET_LINE_SEGMENT_CACHE = "SET_LINE_SEGMENT_CACHE"
