// actions indicating the internet connection to certain services failed
export const SET_MVG_CONNECTIVITY_FLAG = "SET_MVG_CONNECTIVITY_FLAG"
export const SET_PROXY_CONNECTIVITY_FLAG = "SET_PROXY_CONNECTIVITY_FLAG"
export const SET_BACKEND_CONNECTIVITY_FLAG = "SET_BACKEND_CONNECTIVITY_FLAG"
export const SET_MVV_CONNECTIVITY_FLAG = "SET_MVV_CONNECTIVITY_FLAG"
