export const INVALID_STATION = "INVALID_STATION"
export const STORAGE_FAIL = "STORAGE_FAIL"

export const ADD_DESTINATION = "ADD_DESTINATION"
export const ADD_DESTINATION_SUCCESS = "ADD_DESTINATION_SUCCESS"
export const ADD_DESTINATION_FAILED = "ADD_DESTINATION_FAILED"

export const GET_DESTINATION = "GET_DESTINATION"
export const GET_DESTINATION_SUCCESS = "GET_DESTINATION_SUCCESS"
export const GET_DESTINATION_FAILED = "GET_DESTINATION_FAILED"

export const CLEAR_DESTINATION = "CLEAR_DESTINATION"
export const CLEAR_DESTINATION_SUCCESS = "CLEAR_DESTINATION_SUCCESS"
export const CLEAR_DESTINATION_FAILED = "CLEAR_DESTINATION_FAILED"

export const REMOVE_DESTINATION = "REMOVE_DESTINATION"
export const REMOVE_DESTINATION_SUCCESS = 'REMOVE_DESTINATION_SUCCESS'
export const REMOVE_DESTINATION_FAILED = "REMOVE_DESTINATION_FAILED"

export const SHOW_DESTINATION_DETAIL = "SHOW_DESTINATION_DETAIL"
