export const TOGGLE_LOCATION_MODE = "TOGGLE_LOCATION_MODE"
export const SET_LOCATION = "SET_LOCATION"
export const SET_LOCATION_SUCCESS = "SET_LOCATION_SUCCESS"
export const SET_LOCATION_FAILED = "SET_LOCATION_FAILED"
